#!/bin/bash
# Install graylog collector sidecar
check_user_permission()
{
clear
	if [ $(id -u) -ne 0 ]
	then
		clear
		echo 'User can not permission install package.'
		echo 'Please Login Root Account.'
		echo 'Thanks!'
		exit $1
	fi
}

Install()
{
	# Download a sidecar package
	echo "Download a sidecar package"
	FILE="collector*"

        if [ -f $FILE ];
        then
           echo "File $FILE  exists."
        else
	wget https://github.com/Graylog2/collector-sidecar/releases/download/0.1.0-beta.1/collector-sidecar_0.1.0-1_amd64.deb
	fi

	# Install
	echo "Install sidecar"
	sudo dpkg -i collector-sidecar_0.1.0-1_amd64.deb

	# Create a system service
	sudo graylog-collector-sidecar -service install
}

Config()
{
	cp collector_sidecar.yml collector_sidecar.yml.bak
	read -p "Nhap duong dan thu muc chua cac file log ma ban muon xem: " log_path
	cat > collector_sidecar.yml <<EOF
server_url: http://graylog.edumall.vn:9000/api/
update_interval: 10
tls_skip_verify: false
send_status: true
list_log_files:
    - $log_path
node_id: graylog-collector-sidecar
collector_id: file:/etc/graylog/collector-sidecar/collector-id
log_path: /var/log/graylog/collector-sidecar
log_rotation_time: 86400
log_max_age: 604800
tags:
    - linux
    - ruby
backends:
    - name: filebeat
      enabled: true
      binary_path: /usr/bin/filebeat
      configuration_path: /etc/graylog/collector-sidecar/generated/filebeat.yml
EOF
	
	echo "Start a service"
	sudo start collector-sidecar
}

main()
{
	check_user_permission
	Install
	Config
}
main
